spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newDBfoHybernateTest
    username: root
    password: Mospwn13295X
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
